version: "3.8"

networks:
  projects:
    external: true

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-oresto
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - projects

  api:
    build:
      context: ./Oresto_Back
      dockerfile: Dockerfile
    container_name: api-oresto
    restart: unless-stopped
    env_file:
      - ./Oresto_Back/.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=projects"

      # -- Router explicite pour l’API --
      - "traefik.http.routers.api-oresto.rule=Host(`api.oresto.io`)"
      - "traefik.http.routers.api-oresto.entrypoints=websecure"
      - "traefik.http.routers.api-oresto.tls.certresolver=letsencrypt"
      - "traefik.http.services.api-oresto.loadbalancer.server.port=3001"
    networks:
      - projects
    depends_on:
      - mongodb

  front:
    build:
      context: ./Oresto_Front
      dockerfile: Dockerfile
      target: production
    container_name: front-oresto
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=projects"

      # -- Router explicite pour le FRONT --
      - "traefik.http.routers.front-oresto.rule=Host(`oresto.io`) || Host(`www.oresto.io`)"
      - "traefik.http.routers.front-oresto.entrypoints=websecure"
      - "traefik.http.routers.front-oresto.tls.certresolver=letsencrypt"
      - "traefik.http.services.front-oresto.loadbalancer.server.port=3000"
    networks:
      - projects

volumes:
  mongo-data:
