http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  routers:
    traefik-dashboard:
      rule: Host(`traefik.oresto.io`)
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: api@internal

    traefik-dashboard-secure:
      rule: Host(`traefik.oresto.io`)
      entryPoints:
        - websecure
      service: api@internal
      tls:
        certResolver: letsencrypt
