log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

api:
  dashboard: true
  insecure: true # À désactiver en prod si tu veux uniquement https

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: contact@oresto.io
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
